version: '3.8'
services:
  web:
    build: .
    ports:
      - "9002:9002" # Match the port used in package.json dev script
    environment:
      - NODE_ENV=development
      # Supabase and GenAI environment variables will be loaded from the .env file
      # Example:
      # - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      # - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      # - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
    volumes:
      - .:/app # Mount the current directory into the container
      - /app/node_modules # Don't mount host node_modules
      - /app/.next # Don't mount host .next folder
    command: npm run dev # Command to start the dev server
  # Add other services like database, Genkit emulator if needed
  # genkit:
  #   build: . # Assuming Genkit setup is in the same Dockerfile or context
  #   ports:
  #     - "3100:3100" # Default Genkit UI port
  #     - "3400:3400" # Default Genkit API port
  #   environment:
  #     - NODE_ENV=development
  #     # Ensure necessary AI keys are available, sourced from .env or host environment
  #     - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run genkit:dev
